app:
  servicos-externos:
    cpf:
      endpoint: https://user-info.herokuapp.com/users/
spring:
  profiles: prod
  application:  
    name: api-votacao      
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
  jmx:
    enabled: false
            
  datasource:
    url: mysql://bc93dbabd9bce7:2a32ed43@us-cdbr-iron-east-01.cleardb.net/heroku_0b67378aa11ff6e?reconnect=true
      